# Generated by Django 4.2.10 on 2024-02-29 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('max_sum', models.PositiveIntegerField(blank=True, null=True, verbose_name='Запланированная сумма')),
                ('collect_sum', models.PositiveIntegerField(default=0, verbose_name='Собранная сумма')),
                ('amount_donaters', models.PositiveIntegerField(default=0, verbose_name='Число людей, сделавших пожертвования')),
                ('end_date', models.DateTimeField(verbose_name='Завершение сбора')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Повод')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_sum', models.PositiveIntegerField(verbose_name='Сумма')),
                ('pay_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect', to='payment.collect', verbose_name='Денежный сбор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donater', to=settings.AUTH_USER_MODEL, verbose_name='Донатер')),
            ],
            options={
                'ordering': ['-pay_date'],
            },
        ),
        migrations.AddField(
            model_name='collect',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.reason'),
        ),
    ]
